version: '3'
services:
  marketing-redis:
    container_name: marketing-redis
    environment:
      [
        APP_NAME=marketing-redis,
        HOSTNAME=marketing-redis,
        REDIS_PASS=948cacc0,
        TZ=Asia/Shanghai
      ]
    image: hubout.xxx.cn/redis:xx
    #ports: ['6379:6379']
    restart: always
    volumes: [ '/data/nas/aim-std/marketing-redis/data:/data' ]
  pdf-server:
    container_name: amc-pdf-server
    image: hubout.xxx.cn/newbanker/pdf-server:202211032047
    ports: [ '38295:8090' ]
    restart: always
    extra_hosts:
      - "xx.xxx.com:192.168.**.**"
    volumes:
      [
        '/data/docker-compose/aim-std/amc-pdf-server:/data',
        '/data/nas/aim-std/amc-pdf-server:/project/logs'
      ]
